apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-configs
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/hub
    repoURL: 'https://github.com/siamaksade/cluster-gitops-examples'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
  project: default