apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: prod-openshift-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
        - key: environment
          operator: In
          values:
            - prod